name: Publish to PYPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel twine 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with pylint
        run: |
          pylint --fail-under=9.0 geochron 

      - name: Pytest
        run: |
          coverage run --source geochron/ -m pytest && coverage report -m --fail-under 99

      - name: MyPy
        run: |
          mypy geostructures --ignore-missing-imports

      - name: Build package
        run: |
          python -m build

        pypi-publish:
      - name: upload release to PyPI
      runs-on: ubuntu-latest
      # Specifying a GitHub environment is optional, but strongly encouraged
      environment: release
      permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
      steps:
        # retrieve your distributions here

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1